# Generated by Django 3.1.5 on 2021-02-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, verbose_name='チーム名')),
                ('result', models.IntegerField(default=0, verbose_name='結果')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, verbose_name='チーム名')),
                ('result', models.IntegerField(default=0, verbose_name='結果')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
            ],
        ),
        migrations.CreateModel(
            name='YourTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, verbose_name='チーム名')),
                ('result', models.IntegerField(default=0, verbose_name='結果')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, verbose_name='チーム名')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam_vote.question', verbose_name='タイトル')),
            ],
        ),
    ]
