# Generated by Django 3.1.5 on 2021-02-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam_vote', '0002_team_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jam_vote.question', verbose_name='タイトル'),
        ),
    ]
