sudo: required

sevices: docker

before_install: 
  - docker-compose up --build -d
  - docker login -u '$HEROKU_USERNAME' -p '$HEROKU_API_KEY' registry.heroku.com

script: 
  - docker-compose exec  --env 'DJANGO_ENV=test' web python3 manage.py migrate
  - docker-compose exec  --env 'DJANGO_ENV=test' web python3 manage.py test


deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app registry.heroku.com/$HEROKU_APP_NAME/web python manage.py migrate
  on:
    branch: prepare-deploy