sudo: required

language: python

sevices: docker

before_install: 
  - docker-compose -f docker-compose.yml up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script: 
  -  docker-compose run web python3 manage.py makemigrations
  -  docker-compose run web python3 manage.py migrate
  -  docker-compose run web python3 manage.py test


deploy:
  provider: script
  skip_cleanup: true
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f DockerFile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME cd /web-version/jam
    heroku run --app $HEROKU_APP_NAME python3 manage.py migrate
  on:
    branch: prepare-deploy